codepkg/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name New</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/TestDepartment.cls
public class TestDepartment {

    public static Department__c createDepartment(String name, ID officeId){
    Department__c department = new Department__c (
    Name = name,
    Office__c = officeId    
    ); 
      
    Database.SaveResult sv = Database.insert(department);  
    return department;
    }
    
    public static Boolean deleteDepartment (ID departmentID){
        try {
            delete new Department__c(ID = departmentID);
        } catch(Exception ex) {
            return false;
        }
        return true;
    }
    
     public static Department__c updateDepartment(ID departmentID, String name){
        Department__c department = new Department__c (
        Id = departmentID,        
        Name = name 
        ); 
        Database.SaveResult sv = Database.update(department);
        return department;
    } 
}