codepkg/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name New</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Employeers</relationshipLabel>
        <relationshipName>Employeers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <defaultValue>&quot;NoFirstName&quot;</defaultValue>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/TestCrud.cls
public class TestCrud {
    
    public static Employee__c createEmployee(String lastName, String firstName, Id departmentId){
        Employee__c employee = new Employee__c (
        Name = lastName,
        First_Name__c = firstName,
        Department__c = departmentId    
        );        
        
        Database.SaveResult sv = Database.insert(employee);
        return employee;
        }
    
    public static Boolean deleteEmployee (Id employeeID){
        try {
            delete new Employee__c(Id = employeeID);
        } catch(Exception ex) {
            return false;
        }
        return true;
        }
     public static Employee__c updateEmployee(Id employeeId, String lastName, String firstName){
        Employee__c employee = new Employee__c (
        Id = employeeId,
        Name = lastName,
        First_Name__c = firstName   
        ); 
         Database.SaveResult sv = Database.update(employee);
         
         return employee;
    } 
}